#ifndef KEYS_H
#define KEYS_H

#include <HID-Project.h>
#include <stdint.h>

static const uint16_t customKeysToKeyCode[] =
{
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_A,               // KEY_A
    KEY_B,               // KEY_B
    KEY_C,               // KEY_C
    KEY_D,               // KEY_D
    KEY_E,               // KEY_E
    KEY_F,               // KEY_F
    KEY_G,               // KEY_G
    KEY_H,               // KEY_H
    KEY_I,               // KEY_I
    KEY_J,               // KEY_J
    KEY_K,               // KEY_K
    KEY_L,               // KEY_L
    KEY_M,               // KEY_M
    KEY_N,               // KEY_N
    KEY_O,               // KEY_O
    KEY_P,               // KEY_P
    KEY_Q,               // KEY_Q
    KEY_R,               // KEY_R
    KEY_S,               // KEY_S
    KEY_T,               // KEY_T
    KEY_U,               // KEY_U
    KEY_V,               // KEY_V
    KEY_W,               // KEY_W
    KEY_X,               // KEY_X
    KEY_Y,               // KEY_Y
    KEY_Z,               // KEY_Z
    KEY_1,               // KEY_1
    KEY_2,               // KEY_2
    KEY_3,               // KEY_3
    KEY_4,               // KEY_4
    KEY_5,               // KEY_5
    KEY_6,               // KEY_6
    KEY_7,               // KEY_7
    KEY_8,               // KEY_8
    KEY_9,               // KEY_9
    KEY_0,               // KEY_0
    KEY_ENTER,               // KEY_ENTER
    KEY_ESC,               // KEY_ESC
    KEY_BACKSPACE,               // KEY_BACKSPACE
    KEY_TAB,               // KEY_TAB
    KEY_SPACE,               // KEY_SPACE
    KEY_MINUS,               // KEY_MINUS
    KEY_LEFT_SHIFT|KEY_0,               // KEY_EQUAL
    KEY_RIGHT_ALT|KEY_SP_ACCENT,               // KEY_LEFT_BRACE
    KEY_RIGHT_ALT|KEY_C_CEDILLA,               // KEY_RIGHT_BRACE
    KEY_RIGHT_ALT|KEY_DEGREE,               // KEY_BACKSLASH
    KEY_RIGHT_ALT|KEY_3,               // KEY_NON_US_NUM
    KEY_LEFT_SHIFT|KEY_COMMA,               // KEY_SEMICOLON
    KEY_QUOTE,               // KEY_QUOTE
    KEY_TILDE,               // KEY_TILDE
    KEY_COMMA,               // KEY_COMMA
    KEY_PERIOD,               // KEY_PERIOD
    KEY_LEFT_SHIFT|KEY_7,               // KEY_SLASH
    KEY_CAPS_LOCK,               // KEY_CAPS_LOCK
    KEY_F1,               // KEY_F1
    KEY_F2,               // KEY_F2
    KEY_F3,               // KEY_F3
    KEY_F4,               // KEY_F4
    KEY_F5,               // KEY_F5
    KEY_F6,               // KEY_F6
    KEY_F7,               // KEY_F7
    KEY_F8,               // KEY_F8
    KEY_F9,               // KEY_F9
    KEY_F10,               // KEY_F10
    KEY_F11,               // KEY_F11
    KEY_F12,               // KEY_F12
    KEY_PRINT,               // KEY_PRINT
    KEY_SCROLL_LOCK,               // KEY_SCROLL_LOCK
    KEY_PAUSE,               // KEY_PAUSE
    KEY_INSERT,               // KEY_INSERT
    KEY_HOME,               // KEY_HOME
    KEY_PAGE_UP,               // KEY_PAGE_UP
    KEY_DELETE,               // KEY_DELETE
    KEY_END,               // KEY_END
    KEY_PAGE_DOWN,               // KEY_PAGE_DOWN
    KEY_RIGHT_ARROW,               // KEY_RIGHT_ARROW
    KEY_LEFT_ARROW,               // KEY_LEFT_ARROW
    KEY_DOWN_ARROW,               // KEY_DOWN_ARROW
    KEY_UP_ARROW,               // KEY_UP_ARROW
    KEY_NUM_LOCK,               // KEY_NUM_LOCK
    KEYPAD_DIVIDE,               // KEYPAD_DIVIDE
    KEYPAD_MULTIPLY,               // KEYPAD_MULTIPLY
    KEYPAD_SUBTRACT,               // KEYPAD_SUBTRACT
    KEYPAD_ADD,               // KEYPAD_ADD
    KEYPAD_ENTER,               // KEYPAD_ENTER
    KEYPAD_1,               // KEYPAD_1
    KEYPAD_2,               // KEYPAD_2
    KEYPAD_3,               // KEYPAD_3
    KEYPAD_4,               // KEYPAD_4
    KEYPAD_5,               // KEYPAD_5
    KEYPAD_6,               // KEYPAD_6
    KEYPAD_7,               // KEYPAD_7
    KEYPAD_8,               // KEYPAD_8
    KEYPAD_9,               // KEYPAD_9
    KEYPAD_0,               // KEYPAD_0
    KEYPAD_DOT,               // KEYPAD_DOT
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_LEFT_CTRL,               // KEY_LEFT_CTRL
    KEY_LEFT_SHIFT,               // KEY_LEFT_SHIFT
    KEY_LEFT_ALT,               // KEY_LEFT_ALT
    KEY_LEFT_GUI,               // KEY_LEFT_GUI
    KEY_RIGHT_CTRL,               // KEY_RIGHT_CTRL
    KEY_RIGHT_SHIFT,               // KEY_RIGHT_SHIFT
    KEY_RIGHT_ALT,               // KEY_RIGHT_ALT
    KEY_RIGHT_GUI,               // KEY_RIGHT_GUI
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    KEY_RESERVED,               // -
    MEDIA_RECORD,               // MEDIA_RECORD
    MEDIA_FAST_FORWARD,               // MEDIA_FAST_FORWARD
    MEDIA_REWIND,               // MEDIA_REWIND
    MEDIA_NEXT,               // MEDIA_NEXT
    MEDIA_PREVIOUS,               // MEDIA_PREVIOUS
    MEDIA_STOP,               // MEDIA_STOP
    MEDIA_PLAY_PAUSE,               // MEDIA_PLAY_PAUSE
    MEDIA_PAUSE,               // MEDIA_PAUSE
    MEDIA_VOLUME_MUTE,               // MEDIA_VOLUME_MUTE
    MEDIA_VOLUME_UP,               // MEDIA_VOLUME_UP
    MEDIA_VOLUME_DOWN,               // MEDIA_VOLUME_DOWN
    CONSUMER_BRIGHTNESS_UP,               // CONSUMER_BRIGHTNESS_UP
    CONSUMER_BRIGHTNESS_DOWN,               // CONSUMER_BRIGHTNESS_DOWN
    CONSUMER_SCREENSAVER,               // CONSUMER_SCREENSAVER
    CONSUMER_EMAIL_READER,               // CONSUMER_EMAIL_READER
    CONSUMER_CALCULATOR,               // CONSUMER_CALCULATOR
    CONSUMER_EXPLORER,               // CONSUMER_EXPLORER
    CONSUMER_BROWSER_HOME,               // CONSUMER_BROWSER_HOME
    CONSUMER_BROWSER_BACK,               // CONSUMER_BROWSER_BACK
    CONSUMER_BROWSER_FORWARD,               // CONSUMER_BROWSER_FORWARD
    CONSUMER_BROWSER_REFRESH,               // CONSUMER_BROWSER_REFRESH
    CONSUMER_BROWSER_BOOKMARKS               // CONSUMER_BROWSER_BOOKMARKS
};


#endif